import Head from "next/head";
import { Collapse, Image, useDisclosure, VStack } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  Grid,
  GridItem,
  Heading,
  Input,
} from "@chakra-ui/react";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { isOpen, onToggle } = useDisclosure();
  const [isVisible, setIsVisible] = useState(true);

  const toggleForms = () => {
    setIsVisible(!isVisible);
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid h="100vh" templateColumns="repeat(5, 1fr)" bg="#ABCDEF">
        <GridItem colSpan={2} h="100%">
          <VStack align="left" spacing={30} h="100%">
            <Image
              src="/ingenious.png"
              alt="INGENIOUS"
              boxSize="65px"
              m="20px"
            ></Image>
            <Image
              src="/city-image.png"
              alt="Building image"
              boxSize={{ base: "270px", md: "420px", lg: "600px" }}
              position="absolute"
              top="50%"
              left={{ base: "15%", md: "30%" }}
              transform="translate(-50%, -50%)"
              zIndex={1}
            ></Image>
          </VStack>
        </GridItem>
        <GridItem
          colSpan={3}
          h="100%"
          bg="#D8EFFD"
          borderRadius="40px 0 0 40px"
        >
          <Flex justifyContent="center" alignItems="center" h="100%">
            <AnimatePresence>
              {isVisible ? (
                <motion.div
                  key="login-form"
                  initial={{ opacity: 0, x: "-100%" }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: "100%" }}
                  transition={{ duration: 0.5 }}
                >
                  <form>
                    <Heading as="h4" size="md" mb="15px">
                      Login
                    </Heading>
                    <FormControl mb="20px">
                      <FormLabel> Username or Email Address:</FormLabel>
                      <Input
                        size="xs"
                        type="email"
                        name="email"
                        placeholder="Username/Email Address"
                        variant="flushed"
                        borderBottom="1px solid #ABCDEF"
                      />
                    </FormControl>
                    <FormControl mb="10px">
                      <FormLabel>Password:</FormLabel>
                      <Input
                        size="xs"
                        type="password"
                        name="password"
                        placeholder="Password"
                        variant="flushed"
                        borderBottom="1px solid #ABCDEF"
                      />
                      <FormHelperText>
                        Forgot Password?
                        <Button onClick={toggleForms}>Click Here</Button>
                      </FormHelperText>
                    </FormControl>
                    <Button type="submit" bgColor="#ABCDEF" color="white">
                      Submit
                    </Button>
                  </form>
                </motion.div>
              ) : (
                <motion.div
                  key="forgot-password-form"
                  initial={{ opacity: 0, x: "100%" }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: "-100%" }}
                  transition={{ duration: 0.5 }}
                >
                  <form>
                    <Heading as="h4" size="md" mb="15px">
                      Forgot Password
                    </Heading>
                    <FormControl mb="20px">
                      <FormLabel> Email Address:</FormLabel>
                      <Input
                        size="xs"
                        type="email"
                        name="email"
                        placeholder="Email Address"
                        variant="flushed"
                        borderBottom="1px solid #ABCDEF"
                      />
                      <FormHelperText mb="10px">
                        Enter email address used to open account
                      </FormHelperText>
                      <Button type="submit" bgColor="#ABCDEF" color="white">
                        Submit
                      </Button>
                      <FormHelperText>
                        Go back to Login page{" "}
                        <Button onClick={toggleForms}>Click Here</Button>
                      </FormHelperText>
                    </FormControl>
                  </form>
                </motion.div>
              )}
            </AnimatePresence>
          </Flex>
        </GridItem>
      </Grid>
    </>
  );
}
