import Head from "next/head";
import { Image, VStack } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  Grid,
  GridItem,
  Heading,
  Input,
} from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid h="100vh" templateColumns="repeat(5, 1fr)" bg="#ABCDEF">
        <GridItem colSpan={2} h="100%">
          <VStack align="left" spacing={30} h="100%">
            <Image
              src="/ingenious.png"
              alt="INGENIOUS"
              boxSize="65px"
              m="20px"
            ></Image>
            <Image
              src="/city-image.png"
              alt="Building image"
              boxSize={{ base: "270px", md: "420px", lg: '600px' }}
              position="absolute"
              top="50%"
              left={{ base: "15%", md: "30%" }}
              transform="translate(-50%, -50%)"
              zIndex={1}
            ></Image>
          </VStack>
        </GridItem>
        <GridItem
          colSpan={3}
          h="100%"
          bg="#D8EFFD"
          borderRadius="40px 0 0 40px"
        >
          <Flex justifyContent="center" alignItems="center" h="100%">
            <form>
              <Heading as="h4" size="md" mb="15px">
                Login
              </Heading>
              <FormControl mb="20px">
                <FormLabel> Username or Email Address:</FormLabel>
                <Input
                  size="xs"
                  type="email"
                  name="email"
                  placeholder="Username/Email Address"
                  variant="flushed"
                  borderBottom="1px solid #ABCDEF"
                />
              </FormControl>
              <FormControl mb="10px">
                <FormLabel>Password:</FormLabel>
                <Input
                  size="xs"
                  type="password"
                  name="password"
                  placeholder="Password"
                  variant="flushed"
                  borderBottom="1px solid #ABCDEF"
                />
                <FormHelperText> Forgot Password? Click here</FormHelperText>
              </FormControl>
              <Button type="submit" bgColor="#ABCDEF" color="white">
                Submit
              </Button>
            </form>
          </Flex>
        </GridItem>
      </Grid>
    </>
  );
}
